/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Milos
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public AdminGUI() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = new ImageIcon(this.getClass().getResource("/resources/test_me_app_icon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        instructor_Gender_ButtonGroup_ = new javax.swing.ButtonGroup();
        student_Gender_ButtonGroup_ = new javax.swing.ButtonGroup();
        header_Panel_ = new javax.swing.JPanel();
        main_Panel_ = new javax.swing.JPanel();
        change_Tabbed_ = new javax.swing.JTabbedPane();
        instructor_Panel_ = new javax.swing.JPanel();
        instructor_ScrollPane_ = new javax.swing.JScrollPane();
        instructor_Table_ = new javax.swing.JTable();
        control_Instructor_Panel_ = new javax.swing.JPanel();
        edit_Instructor_Button_ = new javax.swing.JButton();
        delete_Instructor_Button_ = new javax.swing.JButton();
        student_Panel_ = new javax.swing.JPanel();
        student_ScrollPane_ = new javax.swing.JScrollPane();
        student_Table_ = new javax.swing.JTable();
        control_Student_Panel_ = new javax.swing.JPanel();
        edit_Student_Button_ = new javax.swing.JButton();
        delete_Student_Button_ = new javax.swing.JButton();
        admin_Panel_ = new javax.swing.JPanel();
        admin_ScrollPane_ = new javax.swing.JScrollPane();
        admin_Table_ = new javax.swing.JTable();
        control_Admin_Panel_ = new javax.swing.JPanel();
        edit_Admin_Button_ = new javax.swing.JButton();
        delete_Admin_Button_ = new javax.swing.JButton();
        god_Admin_Panel_ = new javax.swing.JPanel();
        god_Admin_ScrollPane_ = new javax.swing.JScrollPane();
        god_Admin_Table_ = new javax.swing.JTable();
        control_God_Admin_Panel_ = new javax.swing.JPanel();
        god_Edit_Admin_Button_ = new javax.swing.JButton();
        god_Delete_Admin_Button_ = new javax.swing.JButton();
        register_Tabbed_ = new javax.swing.JTabbedPane();
        register_Instructor_Panel_ = new javax.swing.JPanel();
        add_Instructor_ScrollPane_ = new javax.swing.JScrollPane();
        add_Instructor_Panel_ = new javax.swing.JPanel();
        instructor_First_Name_Label_ = new javax.swing.JLabel();
        instructor_First_Name_Field_ = new javax.swing.JTextField();
        instructor_Last_Name_Label_ = new javax.swing.JLabel();
        instructor_Last_Name_Field_ = new javax.swing.JTextField();
        instructor_Initials_Label_ = new javax.swing.JLabel();
        instructor_Initials_Field_ = new javax.swing.JTextField();
        instructor_Phone_Number_Label_ = new javax.swing.JLabel();
        instructor_Phone_Number_Field_ = new javax.swing.JTextField();
        instructor_Gender_Label_ = new javax.swing.JLabel();
        instructor_Gender_Male_ = new javax.swing.JRadioButton();
        instructor_Gender_Female_ = new javax.swing.JRadioButton();
        instructor_Birthdate_DateChooser_ = new com.toedter.calendar.JDateChooser();
        instructor_Email_Label_ = new javax.swing.JLabel();
        instructor_Email_Field_ = new javax.swing.JTextField();
        instructor_Password_Label_ = new javax.swing.JLabel();
        instructor_Password_Field_ = new javax.swing.JTextField();
        add_Instructor_Button_ = new javax.swing.JButton();
        register_Student_Panel_ = new javax.swing.JPanel();
        add_Student_ScrollPane_ = new javax.swing.JScrollPane();
        add_Student_Panel_ = new javax.swing.JPanel();
        student_First_Name_Label_ = new javax.swing.JLabel();
        student_First_Name_Field_ = new javax.swing.JTextField();
        student_Last_Name_Label_ = new javax.swing.JLabel();
        student_Last_Name_Field_ = new javax.swing.JTextField();
        student_City_Label_ = new javax.swing.JLabel();
        student_City_Field_ = new javax.swing.JTextField();
        student_Street_Label_ = new javax.swing.JLabel();
        student_Street_Field_ = new javax.swing.JTextField();
        student_Postal_Code_Label_ = new javax.swing.JLabel();
        student_Postal_Code_Field_ = new javax.swing.JTextField();
        student_Birthdate_Label_ = new javax.swing.JLabel();
        student_Birthdate_DateChooser_ = new com.toedter.calendar.JDateChooser();
        student_Gender_Label_ = new javax.swing.JLabel();
        student_Gender_Male_ = new javax.swing.JRadioButton();
        student_Gender_Female_ = new javax.swing.JRadioButton();
        student_Instructor_Label_ = new javax.swing.JLabel();
        student_Instructor_ComboBox_ = new javax.swing.JComboBox<>();
        student_Email_Label_ = new javax.swing.JLabel();
        student_Email_Field_ = new javax.swing.JTextField();
        student_Password_Label_ = new javax.swing.JLabel();
        student_Password_Field_ = new javax.swing.JTextField();
        add_Student_Button_ = new javax.swing.JButton();
        register_Admin_Panel_ = new javax.swing.JPanel();
        add_Admin_ScrollPane_ = new javax.swing.JScrollPane();
        add_Admin_Panel_ = new javax.swing.JPanel();
        admin_First_Name_Label_ = new javax.swing.JLabel();
        admin_First_Name_Field_ = new javax.swing.JTextField();
        admin_Last_Name_Label_ = new javax.swing.JLabel();
        admin_Last_Name_Field_ = new javax.swing.JTextField();
        admin_Email_Label_ = new javax.swing.JLabel();
        admin_Email_Field_ = new javax.swing.JTextField();
        admin_Phone_Number_Label_ = new javax.swing.JLabel();
        admin_Phone_Number_Field_ = new javax.swing.JTextField();
        admin_Username_Label_ = new javax.swing.JLabel();
        admin_Username_Field_ = new javax.swing.JTextField();
        admin_Password_Label_ = new javax.swing.JLabel();
        admin_Password_Field_ = new javax.swing.JTextField();
        add_Admin_Button_ = new javax.swing.JButton();
        footer_Panel_ = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 650));
        setSize(new java.awt.Dimension(950, 650));

        javax.swing.GroupLayout header_Panel_Layout = new javax.swing.GroupLayout(header_Panel_);
        header_Panel_.setLayout(header_Panel_Layout);
        header_Panel_Layout.setHorizontalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        header_Panel_Layout.setVerticalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(header_Panel_, java.awt.BorderLayout.NORTH);

        main_Panel_.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        instructor_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        instructor_Table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Instructor ID", "Email", "Password", "First Name", "Last Name", "Initials", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        instructor_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        instructor_ScrollPane_.setViewportView(instructor_Table_);

        instructor_Panel_.add(instructor_ScrollPane_, java.awt.BorderLayout.CENTER);

        control_Instructor_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        edit_Instructor_Button_.setText("Edit");
        control_Instructor_Panel_.add(edit_Instructor_Button_);

        delete_Instructor_Button_.setText("Delete");
        control_Instructor_Panel_.add(delete_Instructor_Button_);

        instructor_Panel_.add(control_Instructor_Panel_, java.awt.BorderLayout.SOUTH);

        change_Tabbed_.addTab("Instructors", instructor_Panel_);

        student_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        student_Table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Student ID", "Email", "Password", "First Name", "Last Name", "City", "Street", "Postal Code", "Instructor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        student_ScrollPane_.setViewportView(student_Table_);

        student_Panel_.add(student_ScrollPane_, java.awt.BorderLayout.CENTER);

        control_Student_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        edit_Student_Button_.setText("Edit");
        control_Student_Panel_.add(edit_Student_Button_);

        delete_Student_Button_.setText("Delete");
        control_Student_Panel_.add(delete_Student_Button_);

        student_Panel_.add(control_Student_Panel_, java.awt.BorderLayout.SOUTH);

        change_Tabbed_.addTab("Students", student_Panel_);

        admin_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        admin_Table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Admin ID", "Username", "Password", "First Name", "Last Name", "Email", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admin_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        admin_ScrollPane_.setViewportView(admin_Table_);

        admin_Panel_.add(admin_ScrollPane_, java.awt.BorderLayout.CENTER);

        control_Admin_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        edit_Admin_Button_.setText("Edit");
        control_Admin_Panel_.add(edit_Admin_Button_);

        delete_Admin_Button_.setText("Delete");
        control_Admin_Panel_.add(delete_Admin_Button_);

        admin_Panel_.add(control_Admin_Panel_, java.awt.BorderLayout.SOUTH);

        change_Tabbed_.addTab("Admins", admin_Panel_);

        god_Admin_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        god_Admin_Table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Admin ID", "First Name", "Last Name", "God ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        god_Admin_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        god_Admin_ScrollPane_.setViewportView(god_Admin_Table_);

        god_Admin_Panel_.add(god_Admin_ScrollPane_, java.awt.BorderLayout.CENTER);

        control_God_Admin_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        god_Edit_Admin_Button_.setText("Edit");
        control_God_Admin_Panel_.add(god_Edit_Admin_Button_);

        god_Delete_Admin_Button_.setText("Delete");
        control_God_Admin_Panel_.add(god_Delete_Admin_Button_);

        god_Admin_Panel_.add(control_God_Admin_Panel_, java.awt.BorderLayout.SOUTH);

        change_Tabbed_.addTab("All Admins", god_Admin_Panel_);

        main_Panel_.add(change_Tabbed_);

        register_Instructor_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        java.awt.GridBagLayout add_Instructor_Panel_Layout = new java.awt.GridBagLayout();
        add_Instructor_Panel_Layout.columnWidths = new int[] {100, 100, 100, 100};
        add_Instructor_Panel_.setLayout(add_Instructor_Panel_Layout);

        instructor_First_Name_Label_.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_First_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_First_Name_Field_, gridBagConstraints);

        instructor_Last_Name_Label_.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Last_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Last_Name_Field_, gridBagConstraints);

        instructor_Initials_Label_.setText("Initials:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Initials_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Initials_Field_, gridBagConstraints);

        instructor_Phone_Number_Label_.setText("Phone Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Phone_Number_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Phone_Number_Field_, gridBagConstraints);

        instructor_Gender_Label_.setText("Gender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Gender_Label_, gridBagConstraints);

        instructor_Gender_ButtonGroup_.add(instructor_Gender_Male_);
        instructor_Gender_Male_.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Gender_Male_, gridBagConstraints);

        instructor_Gender_ButtonGroup_.add(instructor_Gender_Female_);
        instructor_Gender_Female_.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Gender_Female_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Birthdate_DateChooser_, gridBagConstraints);

        instructor_Email_Label_.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Email_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Email_Field_, gridBagConstraints);

        instructor_Password_Label_.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Password_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Instructor_Panel_.add(instructor_Password_Field_, gridBagConstraints);

        add_Instructor_ScrollPane_.setViewportView(add_Instructor_Panel_);

        register_Instructor_Panel_.add(add_Instructor_ScrollPane_, java.awt.BorderLayout.CENTER);

        add_Instructor_Button_.setText("Add");
        register_Instructor_Panel_.add(add_Instructor_Button_, java.awt.BorderLayout.SOUTH);

        register_Tabbed_.addTab("Register Instructor", register_Instructor_Panel_);

        register_Student_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        java.awt.GridBagLayout add_Student_Panel_Layout = new java.awt.GridBagLayout();
        add_Student_Panel_Layout.columnWidths = new int[] {100, 100, 100, 100};
        add_Student_Panel_.setLayout(add_Student_Panel_Layout);

        student_First_Name_Label_.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_First_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_First_Name_Field_, gridBagConstraints);

        student_Last_Name_Label_.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Last_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Last_Name_Field_, gridBagConstraints);

        student_City_Label_.setText("City:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_City_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_City_Field_, gridBagConstraints);

        student_Street_Label_.setText("Street:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Street_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Street_Field_, gridBagConstraints);

        student_Postal_Code_Label_.setText("Postal Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Postal_Code_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Postal_Code_Field_, gridBagConstraints);

        student_Birthdate_Label_.setText("Birthdate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Birthdate_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Birthdate_DateChooser_, gridBagConstraints);

        student_Gender_Label_.setText("Gender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Gender_Label_, gridBagConstraints);

        student_Gender_ButtonGroup_.add(student_Gender_Male_);
        student_Gender_Male_.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Gender_Male_, gridBagConstraints);

        student_Gender_ButtonGroup_.add(student_Gender_Female_);
        student_Gender_Female_.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Gender_Female_, gridBagConstraints);

        student_Instructor_Label_.setText("Instructor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Instructor_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Instructor_ComboBox_, gridBagConstraints);

        student_Email_Label_.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Email_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Email_Field_, gridBagConstraints);

        student_Password_Label_.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Password_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Student_Panel_.add(student_Password_Field_, gridBagConstraints);

        add_Student_ScrollPane_.setViewportView(add_Student_Panel_);

        register_Student_Panel_.add(add_Student_ScrollPane_, java.awt.BorderLayout.CENTER);

        add_Student_Button_.setText("Add");
        register_Student_Panel_.add(add_Student_Button_, java.awt.BorderLayout.SOUTH);

        register_Tabbed_.addTab("Register Student", register_Student_Panel_);

        register_Admin_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        java.awt.GridBagLayout add_Admin_Panel_Layout = new java.awt.GridBagLayout();
        add_Admin_Panel_Layout.columnWidths = new int[] {100, 100, 150};
        add_Admin_Panel_.setLayout(add_Admin_Panel_Layout);

        admin_First_Name_Label_.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_First_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_First_Name_Field_, gridBagConstraints);

        admin_Last_Name_Label_.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Last_Name_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Last_Name_Field_, gridBagConstraints);

        admin_Email_Label_.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Email_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Email_Field_, gridBagConstraints);

        admin_Phone_Number_Label_.setText("Phone Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Phone_Number_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Phone_Number_Field_, gridBagConstraints);

        admin_Username_Label_.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Username_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Username_Field_, gridBagConstraints);

        admin_Password_Label_.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Password_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add_Admin_Panel_.add(admin_Password_Field_, gridBagConstraints);

        add_Admin_ScrollPane_.setViewportView(add_Admin_Panel_);

        register_Admin_Panel_.add(add_Admin_ScrollPane_, java.awt.BorderLayout.CENTER);

        add_Admin_Button_.setText("Add");
        register_Admin_Panel_.add(add_Admin_Button_, java.awt.BorderLayout.SOUTH);

        register_Tabbed_.addTab("Register Admin", register_Admin_Panel_);

        main_Panel_.add(register_Tabbed_);

        getContentPane().add(main_Panel_, java.awt.BorderLayout.CENTER);

        footer_Panel_.setPreferredSize(new java.awt.Dimension(950, 25));

        javax.swing.GroupLayout footer_Panel_Layout = new javax.swing.GroupLayout(footer_Panel_);
        footer_Panel_.setLayout(footer_Panel_Layout);
        footer_Panel_Layout.setHorizontalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        footer_Panel_Layout.setVerticalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(footer_Panel_, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAdd_Admin_Button_() {
        return add_Admin_Button_;
    }

    public JButton getAdd_Instructor_Button_() {
        return add_Instructor_Button_;
    }

    public JButton getAdd_Student_Button_() {
        return add_Student_Button_;
    }

    public JTextField getAdmin_Email_Field_() {
        return admin_Email_Field_;
    }

    public JTextField getAdmin_First_Name_Field_() {
        return admin_First_Name_Field_;
    }

    public JTextField getAdmin_Last_Name_Field_() {
        return admin_Last_Name_Field_;
    }

    public JTextField getAdmin_Password_Field_() {
        return admin_Password_Field_;
    }

    public JTextField getAdmin_Phone_Number_Field_() {
        return admin_Phone_Number_Field_;
    }

    public JTextField getAdmin_Username_Field_() {
        return admin_Username_Field_;
    }

    public JDateChooser getInstructor_Birthdate_DateChooser_() {
        return instructor_Birthdate_DateChooser_;
    }

    public JTextField getInstructor_Email_Field_() {
        return instructor_Email_Field_;
    }

    public JTextField getInstructor_First_Name_Field_() {
        return instructor_First_Name_Field_;
    }

    public ButtonGroup getInstructor_Gender_ButtonGroup_() {
        return instructor_Gender_ButtonGroup_;
    }

    public JRadioButton getInstructor_Gender_Female_() {
        return instructor_Gender_Female_;
    }

    public JRadioButton getInstructor_Gender_Male_() {
        return instructor_Gender_Male_;
    }

    public JTextField getInstructor_Initials_Field_() {
        return instructor_Initials_Field_;
    }

    public JTextField getInstructor_Last_Name_Field_() {
        return instructor_Last_Name_Field_;
    }

    public JTextField getInstructor_Password_Field_() {
        return instructor_Password_Field_;
    }

    public JTextField getInstructor_Phone_Number_Field_() {
        return instructor_Phone_Number_Field_;
    }

    public JDateChooser getStudent_Birthdate_DateChooser_() {
        return student_Birthdate_DateChooser_;
    }

    public JTextField getStudent_City_Field_() {
        return student_City_Field_;
    }

    public JTextField getStudent_Email_Field_() {
        return student_Email_Field_;
    }

    public JTextField getStudent_First_Name_Field_() {
        return student_First_Name_Field_;
    }

    public ButtonGroup getStudent_Gender_ButtonGroup_() {
        return student_Gender_ButtonGroup_;
    }

    public JRadioButton getStudent_Gender_Female_() {
        return student_Gender_Female_;
    }

    public JRadioButton getStudent_Gender_Male_() {
        return student_Gender_Male_;
    }

    public JComboBox<String> getStudent_Instructor_ComboBox_() {
        return student_Instructor_ComboBox_;
    }

    public JTextField getStudent_Last_Name_Field_() {
        return student_Last_Name_Field_;
    }

    public JTextField getStudent_Password_Field_() {
        return student_Password_Field_;
    }

    public JTextField getStudent_Postal_Code_Field_() {
        return student_Postal_Code_Field_;
    }

    public JTextField getStudent_Street_Field_() {
        return student_Street_Field_;
    }

    public JTable getAdmin_Table_() {
        return admin_Table_;
    }

    public JButton getDelete_Admin_Button_() {
        return delete_Admin_Button_;
    }

    public JButton getDelete_Instructor_Button_() {
        return delete_Instructor_Button_;
    }

    public JButton getDelete_Student_Button_() {
        return delete_Student_Button_;
    }

    public JButton getEdit_Admin_Button_() {
        return edit_Admin_Button_;
    }

    public JButton getEdit_Instructor_Button_() {
        return edit_Instructor_Button_;
    }

    public JButton getEdit_Student_Button_() {
        return edit_Student_Button_;
    }

    public JTable getInstructor_Table_() {
        return instructor_Table_;
    }

    public JTable getStudent_Table_() {
        return student_Table_;
    }

    public JTabbedPane getControl_Tabbed_() {
        return change_Tabbed_;
    }

    public JTabbedPane getRegister_Tabbed_() {
        return register_Tabbed_;
    }

    public JTable getGod_Admin_Table_() {
        return god_Admin_Table_;
    }

    public JButton getGod_Delete_Admin_Button_() {
        return god_Delete_Admin_Button_;
    }

    public JButton getGod_Edit_Admin_Button_() {
        return god_Edit_Admin_Button_;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Admin_Button_;
    private javax.swing.JPanel add_Admin_Panel_;
    private javax.swing.JScrollPane add_Admin_ScrollPane_;
    private javax.swing.JButton add_Instructor_Button_;
    private javax.swing.JPanel add_Instructor_Panel_;
    private javax.swing.JScrollPane add_Instructor_ScrollPane_;
    private javax.swing.JButton add_Student_Button_;
    private javax.swing.JPanel add_Student_Panel_;
    private javax.swing.JScrollPane add_Student_ScrollPane_;
    private javax.swing.JTextField admin_Email_Field_;
    private javax.swing.JLabel admin_Email_Label_;
    private javax.swing.JTextField admin_First_Name_Field_;
    private javax.swing.JLabel admin_First_Name_Label_;
    private javax.swing.JTextField admin_Last_Name_Field_;
    private javax.swing.JLabel admin_Last_Name_Label_;
    private javax.swing.JPanel admin_Panel_;
    private javax.swing.JTextField admin_Password_Field_;
    private javax.swing.JLabel admin_Password_Label_;
    private javax.swing.JTextField admin_Phone_Number_Field_;
    private javax.swing.JLabel admin_Phone_Number_Label_;
    private javax.swing.JScrollPane admin_ScrollPane_;
    private javax.swing.JTable admin_Table_;
    private javax.swing.JTextField admin_Username_Field_;
    private javax.swing.JLabel admin_Username_Label_;
    private javax.swing.JTabbedPane change_Tabbed_;
    private javax.swing.JPanel control_Admin_Panel_;
    private javax.swing.JPanel control_God_Admin_Panel_;
    private javax.swing.JPanel control_Instructor_Panel_;
    private javax.swing.JPanel control_Student_Panel_;
    private javax.swing.JButton delete_Admin_Button_;
    private javax.swing.JButton delete_Instructor_Button_;
    private javax.swing.JButton delete_Student_Button_;
    private javax.swing.JButton edit_Admin_Button_;
    private javax.swing.JButton edit_Instructor_Button_;
    private javax.swing.JButton edit_Student_Button_;
    private javax.swing.JPanel footer_Panel_;
    private javax.swing.JPanel god_Admin_Panel_;
    private javax.swing.JScrollPane god_Admin_ScrollPane_;
    private javax.swing.JTable god_Admin_Table_;
    private javax.swing.JButton god_Delete_Admin_Button_;
    private javax.swing.JButton god_Edit_Admin_Button_;
    private javax.swing.JPanel header_Panel_;
    private com.toedter.calendar.JDateChooser instructor_Birthdate_DateChooser_;
    private javax.swing.JTextField instructor_Email_Field_;
    private javax.swing.JLabel instructor_Email_Label_;
    private javax.swing.JTextField instructor_First_Name_Field_;
    private javax.swing.JLabel instructor_First_Name_Label_;
    private javax.swing.ButtonGroup instructor_Gender_ButtonGroup_;
    private javax.swing.JRadioButton instructor_Gender_Female_;
    private javax.swing.JLabel instructor_Gender_Label_;
    private javax.swing.JRadioButton instructor_Gender_Male_;
    private javax.swing.JTextField instructor_Initials_Field_;
    private javax.swing.JLabel instructor_Initials_Label_;
    private javax.swing.JTextField instructor_Last_Name_Field_;
    private javax.swing.JLabel instructor_Last_Name_Label_;
    private javax.swing.JPanel instructor_Panel_;
    private javax.swing.JTextField instructor_Password_Field_;
    private javax.swing.JLabel instructor_Password_Label_;
    private javax.swing.JTextField instructor_Phone_Number_Field_;
    private javax.swing.JLabel instructor_Phone_Number_Label_;
    private javax.swing.JScrollPane instructor_ScrollPane_;
    private javax.swing.JTable instructor_Table_;
    private javax.swing.JPanel main_Panel_;
    private javax.swing.JPanel register_Admin_Panel_;
    private javax.swing.JPanel register_Instructor_Panel_;
    private javax.swing.JPanel register_Student_Panel_;
    private javax.swing.JTabbedPane register_Tabbed_;
    private com.toedter.calendar.JDateChooser student_Birthdate_DateChooser_;
    private javax.swing.JLabel student_Birthdate_Label_;
    private javax.swing.JTextField student_City_Field_;
    private javax.swing.JLabel student_City_Label_;
    private javax.swing.JTextField student_Email_Field_;
    private javax.swing.JLabel student_Email_Label_;
    private javax.swing.JTextField student_First_Name_Field_;
    private javax.swing.JLabel student_First_Name_Label_;
    private javax.swing.ButtonGroup student_Gender_ButtonGroup_;
    private javax.swing.JRadioButton student_Gender_Female_;
    private javax.swing.JLabel student_Gender_Label_;
    private javax.swing.JRadioButton student_Gender_Male_;
    private javax.swing.JComboBox<String> student_Instructor_ComboBox_;
    private javax.swing.JLabel student_Instructor_Label_;
    private javax.swing.JTextField student_Last_Name_Field_;
    private javax.swing.JLabel student_Last_Name_Label_;
    private javax.swing.JPanel student_Panel_;
    private javax.swing.JTextField student_Password_Field_;
    private javax.swing.JLabel student_Password_Label_;
    private javax.swing.JTextField student_Postal_Code_Field_;
    private javax.swing.JLabel student_Postal_Code_Label_;
    private javax.swing.JScrollPane student_ScrollPane_;
    private javax.swing.JTextField student_Street_Field_;
    private javax.swing.JLabel student_Street_Label_;
    private javax.swing.JTable student_Table_;
    // End of variables declaration//GEN-END:variables
}
