/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import service.Observer;

/**
 *
 * @author Milos
 */
public class LoginGUI extends javax.swing.JFrame implements Subject {

    private Observer observer;

    /**
     * Creates new form NewJFrame1
     *
     */
    public LoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
        login_ScrollPane_.getVerticalScrollBar().setUnitIncrement(15);
        Image icon = new ImageIcon(this.getClass().getResource("/resources/test_me_app_icon.png")).getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        login_ScrollPane_ = new javax.swing.JScrollPane();
        login_Panel_ = new javax.swing.JPanel();
        logo_Label_ = new javax.swing.JLabel();
        username_Email_Label_ = new javax.swing.JLabel();
        username_Email_Field_ = new javax.swing.JTextField();
        password_Label_ = new javax.swing.JLabel();
        password_Field_ = new javax.swing.JPasswordField();
        show_Password_CheckBox_ = new javax.swing.JCheckBox();
        login_Button_ = new javax.swing.JButton();
        generic_Separator_ = new javax.swing.JSeparator();
        info_Label_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        login_Panel_.setLayout(new java.awt.GridBagLayout());

        logo_Label_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(logo_Label_, gridBagConstraints);

        username_Email_Label_.setText("Username / Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        login_Panel_.add(username_Email_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(username_Email_Field_, gridBagConstraints);

        password_Label_.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(password_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(password_Field_, gridBagConstraints);

        show_Password_CheckBox_.setText("Show Password?");
        show_Password_CheckBox_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_Password_CheckBox_MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(show_Password_CheckBox_, gridBagConstraints);

        login_Button_.setText("Login!");
        login_Button_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_Button_MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(login_Button_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        login_Panel_.add(generic_Separator_, gridBagConstraints);

        info_Label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info_Label_.setText("coded with <3 by Miloš Ilić");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login_Panel_.add(info_Label_, gridBagConstraints);

        login_ScrollPane_.setViewportView(login_Panel_);

        getContentPane().add(login_ScrollPane_, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_Button_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_Button_MouseClicked

        String usernameEmail = username_Email_Field_.getText();
        String password = new String(password_Field_.getPassword());
        fireAction(usernameEmail, password);
    }//GEN-LAST:event_login_Button_MouseClicked

    private void show_Password_CheckBox_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_Password_CheckBox_MouseClicked

        if (show_Password_CheckBox_.isSelected()) {
            password_Field_.setEchoChar((char) 0);
        } else {
            password_Field_.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_show_Password_CheckBox_MouseClicked

    private void fireAction(String usernameEmail, String password) {
        if (observer != null) {
            observer.performAction(usernameEmail, password);
        }
    }

    @Override
    public void setObserver(Observer observer) {
        this.observer = observer;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator generic_Separator_;
    private javax.swing.JLabel info_Label_;
    private javax.swing.JButton login_Button_;
    private javax.swing.JPanel login_Panel_;
    private javax.swing.JScrollPane login_ScrollPane_;
    private javax.swing.JLabel logo_Label_;
    private javax.swing.JPasswordField password_Field_;
    private javax.swing.JLabel password_Label_;
    private javax.swing.JCheckBox show_Password_CheckBox_;
    private javax.swing.JTextField username_Email_Field_;
    private javax.swing.JLabel username_Email_Label_;
    // End of variables declaration//GEN-END:variables
}
