/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import facade.SignInFacade;
import javax.swing.UIManager;

/**
 *
 * @author Milos
 */
public class SignInFrame extends javax.swing.JFrame {

    private SignInFacade sif;

    /**
     * Creates new form NewJFrame1
     */
    public SignInFrame() {
        initComponents();
        setLocationRelativeTo(null);
        sif = new SignInFacade(this);
        sign_In_ScrollPane_.getVerticalScrollBar().setUnitIncrement(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sign_In_ScrollPane_ = new javax.swing.JScrollPane();
        sign_In_Panel_ = new javax.swing.JPanel();
        test_Me_Label_ = new javax.swing.JLabel();
        icon_Label_ = new javax.swing.JLabel();
        username_Email_Label_ = new javax.swing.JLabel();
        username_Email_Field_ = new javax.swing.JTextField();
        password_Label_ = new javax.swing.JLabel();
        password_Field_ = new javax.swing.JPasswordField();
        show_Password_CheckBox_ = new javax.swing.JCheckBox();
        sign_In_Button_ = new javax.swing.JButton();
        generic_Separator_ = new javax.swing.JSeparator();
        info_Label_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        sign_In_Panel_.setLayout(new java.awt.GridBagLayout());

        test_Me_Label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        test_Me_Label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        test_Me_Label_.setText("Test Me!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 100);
        sign_In_Panel_.add(test_Me_Label_, gridBagConstraints);

        icon_Label_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/test_app_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 100, 5, 5);
        sign_In_Panel_.add(icon_Label_, gridBagConstraints);

        username_Email_Label_.setText("Username / Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        sign_In_Panel_.add(username_Email_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(username_Email_Field_, gridBagConstraints);

        password_Label_.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(password_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(password_Field_, gridBagConstraints);

        show_Password_CheckBox_.setText("Show Password?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(show_Password_CheckBox_, gridBagConstraints);

        sign_In_Button_.setText("Sign In!");
        sign_In_Button_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_In_Button_MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(sign_In_Button_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        sign_In_Panel_.add(generic_Separator_, gridBagConstraints);

        info_Label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info_Label_.setText("coded with <3 by Miloš Ilić");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        sign_In_Panel_.add(info_Label_, gridBagConstraints);

        sign_In_ScrollPane_.setViewportView(sign_In_Panel_);

        getContentPane().add(sign_In_ScrollPane_, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sign_In_Button_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_In_Button_MouseClicked

        sif.signInCheck(username_Email_Field_, password_Field_);
    }//GEN-LAST:event_sign_In_Button_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator generic_Separator_;
    private javax.swing.JLabel icon_Label_;
    private javax.swing.JLabel info_Label_;
    private javax.swing.JPasswordField password_Field_;
    private javax.swing.JLabel password_Label_;
    private javax.swing.JCheckBox show_Password_CheckBox_;
    private javax.swing.JButton sign_In_Button_;
    private javax.swing.JPanel sign_In_Panel_;
    private javax.swing.JScrollPane sign_In_ScrollPane_;
    private javax.swing.JLabel test_Me_Label_;
    private javax.swing.JTextField username_Email_Field_;
    private javax.swing.JLabel username_Email_Label_;
    // End of variables declaration//GEN-END:variables
}
