/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Milos
 */
public class InstructorGUI extends javax.swing.JFrame {

    /**
     * Creates new form Instructor
     */
    public InstructorGUI() {
        initComponents();
        setLocationRelativeTo(null);
        submitted_Test_Table_.putClientProperty("terminateEditOnFocusLost", true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header_Panel_ = new javax.swing.JPanel();
        main_Panel_ = new javax.swing.JPanel();
        instructor_Panel_ = new javax.swing.JPanel();
        student_Panel_ = new javax.swing.JPanel();
        student_Label_ = new javax.swing.JLabel();
        student_ScrollPane_ = new javax.swing.JScrollPane();
        student_Table_ = new javax.swing.JTable();
        below_Panel_ = new javax.swing.JPanel();
        test_And_Taken_By_Panel_ = new javax.swing.JPanel();
        test_And_Taken_By_Info_Panel_ = new javax.swing.JPanel();
        test_And_Taken_By_Label_Panel_ = new javax.swing.JPanel();
        test_Label_ = new javax.swing.JLabel();
        taken_By_Label_ = new javax.swing.JLabel();
        test_List_And_Taken_By_List_Panel_ = new javax.swing.JPanel();
        test_ScrollPane_ = new javax.swing.JScrollPane();
        test_List_ = new javax.swing.JList<>();
        taken_By_ScrollPane_ = new javax.swing.JScrollPane();
        taken_By_List_ = new javax.swing.JList<>();
        create_Test_Button_ = new javax.swing.JButton();
        submitted_Test_Panel_ = new javax.swing.JPanel();
        submitted_Test_Info_Panel_ = new javax.swing.JPanel();
        submitted_Test_Label_ = new javax.swing.JLabel();
        submitted_Test_ScrollPane = new javax.swing.JScrollPane();
        submitted_Test_Table_ = new javax.swing.JTable();
        submitted_Test_Buttons_Panel_ = new javax.swing.JPanel();
        look_Up_Submitted_Test_Button_ = new javax.swing.JButton();
        grade_Submitted_Test__Button_ = new javax.swing.JButton();
        create_Test_Panel_ = new javax.swing.JPanel();
        test_Info_Panel_ = new javax.swing.JPanel();
        test_Panel_ = new javax.swing.JPanel();
        back_To_Instructor_Button_1_ = new javax.swing.JButton();
        test_Question_Task_Info_Panel_ = new javax.swing.JPanel();
        test_Question_Task_Label_Panel_ = new javax.swing.JPanel();
        test_Name_Label_ = new javax.swing.JLabel();
        test_Description_Label_ = new javax.swing.JLabel();
        number_Of_Questions_Label_ = new javax.swing.JLabel();
        number_Of_Tasks_Label_ = new javax.swing.JLabel();
        test_Question_Task_Text_Panel_ = new javax.swing.JPanel();
        test_Name_Field_ = new javax.swing.JTextField();
        test_Description_Field_ = new javax.swing.JTextField();
        question_Number_Label_ = new javax.swing.JLabel();
        task_Number_Label_ = new javax.swing.JLabel();
        compose_Test_TabbedPane_ = new javax.swing.JTabbedPane();
        question_Panel_ = new javax.swing.JPanel();
        question_Info_ScrollPane_ = new javax.swing.JScrollPane();
        question_Info_Panel_ = new javax.swing.JPanel();
        question_Label_ = new javax.swing.JLabel();
        question_Field_ = new javax.swing.JTextField();
        option1_Label_ = new javax.swing.JLabel();
        option1_Field_ = new javax.swing.JTextField();
        option2_Label_ = new javax.swing.JLabel();
        option2_Field_ = new javax.swing.JTextField();
        option3_Label_ = new javax.swing.JLabel();
        option3_Field_ = new javax.swing.JTextField();
        option4_Label_ = new javax.swing.JLabel();
        option4_Field_ = new javax.swing.JTextField();
        correct_Answer_Label_ = new javax.swing.JLabel();
        correct_Answer_ComboBox_ = new javax.swing.JComboBox<>();
        add_Question_Button_ = new javax.swing.JButton();
        task_Panel_ = new javax.swing.JPanel();
        task_Info_ScrollPane_ = new javax.swing.JScrollPane();
        task_Info_Panel_ = new javax.swing.JPanel();
        task_Description_Label_ = new javax.swing.JLabel();
        task_Description_Field_ = new javax.swing.JTextField();
        code_Label_ = new javax.swing.JLabel();
        code_TextArea_ = new javax.swing.JTextArea();
        add_Task_Button_ = new javax.swing.JButton();
        finish_Test_Button_ = new javax.swing.JButton();
        look_Up_Submitted_Test_Panel_ = new javax.swing.JPanel();
        submitted_Test_Look_Up_Panel_ = new javax.swing.JPanel();
        submitted_Question_ScrollPane_ = new javax.swing.JScrollPane();
        submitted_Question_Panel_ = new javax.swing.JPanel();
        submitted_Task_ScrollPane_ = new javax.swing.JScrollPane();
        submitted_Task_Panel_ = new javax.swing.JPanel();
        back_To_Instructor_Button_2_ = new javax.swing.JButton();
        footer_Panel_ = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 650));

        header_Panel_.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout header_Panel_Layout = new javax.swing.GroupLayout(header_Panel_);
        header_Panel_.setLayout(header_Panel_Layout);
        header_Panel_Layout.setHorizontalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        header_Panel_Layout.setVerticalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(header_Panel_, java.awt.BorderLayout.NORTH);

        main_Panel_.setPreferredSize(new java.awt.Dimension(950, 650));
        main_Panel_.setLayout(new java.awt.CardLayout());

        instructor_Panel_.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        student_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        student_Label_.setText("Students:");
        student_Panel_.add(student_Label_, java.awt.BorderLayout.NORTH);

        student_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        student_ScrollPane_.setViewportView(student_Table_);

        student_Panel_.add(student_ScrollPane_, java.awt.BorderLayout.CENTER);

        instructor_Panel_.add(student_Panel_);

        below_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        test_And_Taken_By_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        test_And_Taken_By_Info_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        test_And_Taken_By_Label_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        test_Label_.setText("Test list:");
        test_And_Taken_By_Label_Panel_.add(test_Label_);

        taken_By_Label_.setText("Taken by:");
        test_And_Taken_By_Label_Panel_.add(taken_By_Label_);

        test_And_Taken_By_Info_Panel_.add(test_And_Taken_By_Label_Panel_, java.awt.BorderLayout.NORTH);

        test_List_And_Taken_By_List_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        test_ScrollPane_.setViewportView(test_List_);

        test_List_And_Taken_By_List_Panel_.add(test_ScrollPane_);

        taken_By_ScrollPane_.setViewportView(taken_By_List_);

        test_List_And_Taken_By_List_Panel_.add(taken_By_ScrollPane_);

        test_And_Taken_By_Info_Panel_.add(test_List_And_Taken_By_List_Panel_, java.awt.BorderLayout.CENTER);

        test_And_Taken_By_Panel_.add(test_And_Taken_By_Info_Panel_, java.awt.BorderLayout.CENTER);

        create_Test_Button_.setText("Create Test!");
        test_And_Taken_By_Panel_.add(create_Test_Button_, java.awt.BorderLayout.SOUTH);

        below_Panel_.add(test_And_Taken_By_Panel_);

        submitted_Test_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        submitted_Test_Info_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        submitted_Test_Label_.setText("Submitted Tests:");
        submitted_Test_Info_Panel_.add(submitted_Test_Label_, java.awt.BorderLayout.NORTH);

        submitted_Test_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        submitted_Test_ScrollPane.setViewportView(submitted_Test_Table_);

        submitted_Test_Info_Panel_.add(submitted_Test_ScrollPane, java.awt.BorderLayout.CENTER);

        submitted_Test_Panel_.add(submitted_Test_Info_Panel_, java.awt.BorderLayout.CENTER);

        submitted_Test_Buttons_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        look_Up_Submitted_Test_Button_.setText("Look Up!");
        submitted_Test_Buttons_Panel_.add(look_Up_Submitted_Test_Button_);

        grade_Submitted_Test__Button_.setText("Grade!");
        submitted_Test_Buttons_Panel_.add(grade_Submitted_Test__Button_);

        submitted_Test_Panel_.add(submitted_Test_Buttons_Panel_, java.awt.BorderLayout.SOUTH);

        below_Panel_.add(submitted_Test_Panel_);

        instructor_Panel_.add(below_Panel_);

        main_Panel_.add(instructor_Panel_, "instructor_Card_");

        create_Test_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        test_Info_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        test_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        back_To_Instructor_Button_1_.setText("Back");
        test_Panel_.add(back_To_Instructor_Button_1_, java.awt.BorderLayout.NORTH);

        test_Question_Task_Info_Panel_.setLayout(new java.awt.GridLayout(1, 2));

        test_Question_Task_Label_Panel_.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        test_Name_Label_.setText("Test Name:");
        test_Question_Task_Label_Panel_.add(test_Name_Label_);

        test_Description_Label_.setText("Test Description:");
        test_Question_Task_Label_Panel_.add(test_Description_Label_);

        number_Of_Questions_Label_.setText("Current Number Of Questions:");
        test_Question_Task_Label_Panel_.add(number_Of_Questions_Label_);

        number_Of_Tasks_Label_.setText("Current Number Of Tasks:");
        test_Question_Task_Label_Panel_.add(number_Of_Tasks_Label_);

        test_Question_Task_Info_Panel_.add(test_Question_Task_Label_Panel_);

        test_Question_Task_Text_Panel_.setLayout(new java.awt.GridLayout(4, 0, 0, 5));
        test_Question_Task_Text_Panel_.add(test_Name_Field_);
        test_Question_Task_Text_Panel_.add(test_Description_Field_);
        test_Question_Task_Text_Panel_.add(question_Number_Label_);
        test_Question_Task_Text_Panel_.add(task_Number_Label_);

        test_Question_Task_Info_Panel_.add(test_Question_Task_Text_Panel_);

        test_Panel_.add(test_Question_Task_Info_Panel_, java.awt.BorderLayout.CENTER);

        test_Info_Panel_.add(test_Panel_, java.awt.BorderLayout.NORTH);

        question_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        question_Info_Panel_.setLayout(new java.awt.GridBagLayout());

        question_Label_.setText("Question:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(question_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(question_Field_, gridBagConstraints);

        option1_Label_.setText("Option 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option1_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option1_Field_, gridBagConstraints);

        option2_Label_.setText("Option 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option2_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option2_Field_, gridBagConstraints);

        option3_Label_.setText("Option 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option3_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option3_Field_, gridBagConstraints);

        option4_Label_.setText("Option 4:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option4_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(option4_Field_, gridBagConstraints);

        correct_Answer_Label_.setText("Answer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(correct_Answer_Label_, gridBagConstraints);

        correct_Answer_ComboBox_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Option 1", "Option 2", "Option 3", "Option 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        question_Info_Panel_.add(correct_Answer_ComboBox_, gridBagConstraints);

        question_Info_ScrollPane_.setViewportView(question_Info_Panel_);

        question_Panel_.add(question_Info_ScrollPane_, java.awt.BorderLayout.CENTER);

        add_Question_Button_.setText("Add");
        question_Panel_.add(add_Question_Button_, java.awt.BorderLayout.SOUTH);

        compose_Test_TabbedPane_.addTab("Question From!", question_Panel_);

        task_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        task_Info_Panel_.setLayout(new java.awt.GridBagLayout());

        task_Description_Label_.setText("Task:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        task_Info_Panel_.add(task_Description_Label_, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        task_Info_Panel_.add(task_Description_Field_, gridBagConstraints);

        code_Label_.setText("Code:");
        code_Label_.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        task_Info_Panel_.add(code_Label_, gridBagConstraints);

        code_TextArea_.setColumns(24);
        code_TextArea_.setRows(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        task_Info_Panel_.add(code_TextArea_, gridBagConstraints);

        task_Info_ScrollPane_.setViewportView(task_Info_Panel_);

        task_Panel_.add(task_Info_ScrollPane_, java.awt.BorderLayout.CENTER);

        add_Task_Button_.setText("Add");
        task_Panel_.add(add_Task_Button_, java.awt.BorderLayout.SOUTH);

        compose_Test_TabbedPane_.addTab("Task Form!", task_Panel_);

        test_Info_Panel_.add(compose_Test_TabbedPane_, java.awt.BorderLayout.CENTER);

        create_Test_Panel_.add(test_Info_Panel_, java.awt.BorderLayout.CENTER);

        finish_Test_Button_.setText("Finish!");
        create_Test_Panel_.add(finish_Test_Button_, java.awt.BorderLayout.SOUTH);

        main_Panel_.add(create_Test_Panel_, "create_Test_Card_");

        look_Up_Submitted_Test_Panel_.setLayout(new java.awt.BorderLayout());

        submitted_Test_Look_Up_Panel_.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout submitted_Question_Panel_Layout = new javax.swing.GroupLayout(submitted_Question_Panel_);
        submitted_Question_Panel_.setLayout(submitted_Question_Panel_Layout);
        submitted_Question_Panel_Layout.setHorizontalGroup(
            submitted_Question_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        submitted_Question_Panel_Layout.setVerticalGroup(
            submitted_Question_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        submitted_Question_ScrollPane_.setViewportView(submitted_Question_Panel_);

        submitted_Test_Look_Up_Panel_.add(submitted_Question_ScrollPane_);

        javax.swing.GroupLayout submitted_Task_Panel_Layout = new javax.swing.GroupLayout(submitted_Task_Panel_);
        submitted_Task_Panel_.setLayout(submitted_Task_Panel_Layout);
        submitted_Task_Panel_Layout.setHorizontalGroup(
            submitted_Task_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        submitted_Task_Panel_Layout.setVerticalGroup(
            submitted_Task_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        submitted_Task_ScrollPane_.setViewportView(submitted_Task_Panel_);

        submitted_Test_Look_Up_Panel_.add(submitted_Task_ScrollPane_);

        look_Up_Submitted_Test_Panel_.add(submitted_Test_Look_Up_Panel_, java.awt.BorderLayout.CENTER);

        back_To_Instructor_Button_2_.setText("Back");
        look_Up_Submitted_Test_Panel_.add(back_To_Instructor_Button_2_, java.awt.BorderLayout.SOUTH);

        main_Panel_.add(look_Up_Submitted_Test_Panel_, "look_Up_Submitted_Test_Card_");

        getContentPane().add(main_Panel_, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout footer_Panel_Layout = new javax.swing.GroupLayout(footer_Panel_);
        footer_Panel_.setLayout(footer_Panel_Layout);
        footer_Panel_Layout.setHorizontalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footer_Panel_Layout.setVerticalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(footer_Panel_, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAdd_Question_Button_() {
        return add_Question_Button_;
    }

    public JButton getAdd_Task_Button_() {
        return add_Task_Button_;
    }

    public JButton getBack_To_Instructor_Button_1_() {
        return back_To_Instructor_Button_1_;
    }

    public JButton getBack_To_Instructor_Button_2_() {
        return back_To_Instructor_Button_2_;
    }

    public JTextArea getCode_TextArea_() {
        return code_TextArea_;
    }

    public JComboBox<String> getCorrect_Answer_ComboBox_() {
        return correct_Answer_ComboBox_;
    }

    public JButton getCreate_Test_Button_() {
        return create_Test_Button_;
    }

    public JButton getFinish_Test_Button_() {
        return finish_Test_Button_;
    }

    public JButton getGrade_Submitted_Test__Button_() {
        return grade_Submitted_Test__Button_;
    }

    public JButton getLook_Up_Submitted_Test_Button_() {
        return look_Up_Submitted_Test_Button_;
    }

    public JPanel getMain_Panel_() {
        return main_Panel_;
    }

    public JTextField getOption1_Field_() {
        return option1_Field_;
    }

    public JTextField getOption2_Field_() {
        return option2_Field_;
    }

    public JTextField getOption3_Field_() {
        return option3_Field_;
    }

    public JTextField getOption4_Field_() {
        return option4_Field_;
    }

    public JTextField getQuestion_Field_() {
        return question_Field_;
    }

    public JLabel getQuestion_Number_Label_() {
        return question_Number_Label_;
    }

    public JLabel getTask_Number_Label_() {
        return task_Number_Label_;
    }

    public JTable getStudent_Table_() {
        return student_Table_;
    }

    public JPanel getSubmitted_Question_Panel_() {
        return submitted_Question_Panel_;
    }

    public JPanel getSubmitted_Task_Panel_() {
        return submitted_Task_Panel_;
    }

    public JTable getSubmitted_Test_Table_() {
        return submitted_Test_Table_;
    }

    public JList<String> getTaken_By_List_() {
        return taken_By_List_;
    }

    public JTextField getTask_Description_Field_() {
        return task_Description_Field_;
    }

    public JTextField getTest_Description_Field_() {
        return test_Description_Field_;
    }

    public JList<String> getTest_List_() {
        return test_List_;
    }

    public JTextField getTest_Name_Field_() {
        return test_Name_Field_;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Question_Button_;
    private javax.swing.JButton add_Task_Button_;
    private javax.swing.JButton back_To_Instructor_Button_1_;
    private javax.swing.JButton back_To_Instructor_Button_2_;
    private javax.swing.JPanel below_Panel_;
    private javax.swing.JLabel code_Label_;
    private javax.swing.JTextArea code_TextArea_;
    private javax.swing.JTabbedPane compose_Test_TabbedPane_;
    private javax.swing.JComboBox<String> correct_Answer_ComboBox_;
    private javax.swing.JLabel correct_Answer_Label_;
    private javax.swing.JButton create_Test_Button_;
    private javax.swing.JPanel create_Test_Panel_;
    private javax.swing.JButton finish_Test_Button_;
    private javax.swing.JPanel footer_Panel_;
    private javax.swing.JButton grade_Submitted_Test__Button_;
    private javax.swing.JPanel header_Panel_;
    private javax.swing.JPanel instructor_Panel_;
    private javax.swing.JButton look_Up_Submitted_Test_Button_;
    private javax.swing.JPanel look_Up_Submitted_Test_Panel_;
    private javax.swing.JPanel main_Panel_;
    private javax.swing.JLabel number_Of_Questions_Label_;
    private javax.swing.JLabel number_Of_Tasks_Label_;
    private javax.swing.JTextField option1_Field_;
    private javax.swing.JLabel option1_Label_;
    private javax.swing.JTextField option2_Field_;
    private javax.swing.JLabel option2_Label_;
    private javax.swing.JTextField option3_Field_;
    private javax.swing.JLabel option3_Label_;
    private javax.swing.JTextField option4_Field_;
    private javax.swing.JLabel option4_Label_;
    private javax.swing.JTextField question_Field_;
    private javax.swing.JPanel question_Info_Panel_;
    private javax.swing.JScrollPane question_Info_ScrollPane_;
    private javax.swing.JLabel question_Label_;
    private javax.swing.JLabel question_Number_Label_;
    private javax.swing.JPanel question_Panel_;
    private javax.swing.JLabel student_Label_;
    private javax.swing.JPanel student_Panel_;
    private javax.swing.JScrollPane student_ScrollPane_;
    private javax.swing.JTable student_Table_;
    private javax.swing.JPanel submitted_Question_Panel_;
    private javax.swing.JScrollPane submitted_Question_ScrollPane_;
    private javax.swing.JPanel submitted_Task_Panel_;
    private javax.swing.JScrollPane submitted_Task_ScrollPane_;
    private javax.swing.JPanel submitted_Test_Buttons_Panel_;
    private javax.swing.JPanel submitted_Test_Info_Panel_;
    private javax.swing.JLabel submitted_Test_Label_;
    private javax.swing.JPanel submitted_Test_Look_Up_Panel_;
    private javax.swing.JPanel submitted_Test_Panel_;
    private javax.swing.JScrollPane submitted_Test_ScrollPane;
    private javax.swing.JTable submitted_Test_Table_;
    private javax.swing.JLabel taken_By_Label_;
    private javax.swing.JList<String> taken_By_List_;
    private javax.swing.JScrollPane taken_By_ScrollPane_;
    private javax.swing.JTextField task_Description_Field_;
    private javax.swing.JLabel task_Description_Label_;
    private javax.swing.JPanel task_Info_Panel_;
    private javax.swing.JScrollPane task_Info_ScrollPane_;
    private javax.swing.JLabel task_Number_Label_;
    private javax.swing.JPanel task_Panel_;
    private javax.swing.JPanel test_And_Taken_By_Info_Panel_;
    private javax.swing.JPanel test_And_Taken_By_Label_Panel_;
    private javax.swing.JPanel test_And_Taken_By_Panel_;
    private javax.swing.JTextField test_Description_Field_;
    private javax.swing.JLabel test_Description_Label_;
    private javax.swing.JPanel test_Info_Panel_;
    private javax.swing.JLabel test_Label_;
    private javax.swing.JList<String> test_List_;
    private javax.swing.JPanel test_List_And_Taken_By_List_Panel_;
    private javax.swing.JTextField test_Name_Field_;
    private javax.swing.JLabel test_Name_Label_;
    private javax.swing.JPanel test_Panel_;
    private javax.swing.JPanel test_Question_Task_Info_Panel_;
    private javax.swing.JPanel test_Question_Task_Label_Panel_;
    private javax.swing.JPanel test_Question_Task_Text_Panel_;
    private javax.swing.JScrollPane test_ScrollPane_;
    // End of variables declaration//GEN-END:variables
}
