/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Milos
 */
public class StudentGUI extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public StudentGUI() {
        initComponents();
        setLocationRelativeTo(null);
        question_ScrollPane_.getVerticalScrollBar().setUnitIncrement(15);
        task_ScrollPane_.getVerticalScrollBar().setUnitIncrement(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header_Panel_ = new javax.swing.JPanel();
        main_Panel_ = new javax.swing.JPanel();
        student_Panel_ = new javax.swing.JPanel();
        student_TabbedPane_ = new javax.swing.JTabbedPane();
        grade_Panel_ = new javax.swing.JPanel();
        submitted_Test_ScrollPane = new javax.swing.JScrollPane();
        submitted_Test_Table_ = new javax.swing.JTable();
        quiz_Panel_ = new javax.swing.JPanel();
        side_Panel_ = new javax.swing.JPanel();
        test_Info_Panel_ = new javax.swing.JPanel();
        student_Average_Score_Label_ = new javax.swing.JLabel();
        list_Of_Test_Panel_ = new javax.swing.JPanel();
        test_ScrollPane_ = new javax.swing.JScrollPane();
        test_List_ = new javax.swing.JList<>();
        test_Description_Panel_ = new javax.swing.JPanel();
        test_Description_Label_ = new javax.swing.JLabel();
        take_Button_ = new javax.swing.JButton();
        chat_Panel_ = new javax.swing.JPanel();
        work_On_The_Test_Panel_ = new javax.swing.JPanel();
        test_Panel_ = new javax.swing.JPanel();
        question_ScrollPane_ = new javax.swing.JScrollPane();
        question_Panel_ = new javax.swing.JPanel();
        task_ScrollPane_ = new javax.swing.JScrollPane();
        task_Panel_ = new javax.swing.JPanel();
        submit_Button_ = new javax.swing.JButton();
        footer_Panel_ = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 650));

        header_Panel_.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout header_Panel_Layout = new javax.swing.GroupLayout(header_Panel_);
        header_Panel_.setLayout(header_Panel_Layout);
        header_Panel_Layout.setHorizontalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        header_Panel_Layout.setVerticalGroup(
            header_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(header_Panel_, java.awt.BorderLayout.NORTH);

        main_Panel_.setPreferredSize(new java.awt.Dimension(950, 650));
        main_Panel_.setLayout(new java.awt.CardLayout());

        student_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        grade_Panel_.setLayout(new java.awt.BorderLayout());

        submitted_Test_Table_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Test ID", "Test Description", "Student ID", "Student Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        submitted_Test_Table_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        submitted_Test_ScrollPane.setViewportView(submitted_Test_Table_);

        grade_Panel_.add(submitted_Test_ScrollPane, java.awt.BorderLayout.CENTER);

        student_TabbedPane_.addTab("Grades", grade_Panel_);

        javax.swing.GroupLayout quiz_Panel_Layout = new javax.swing.GroupLayout(quiz_Panel_);
        quiz_Panel_.setLayout(quiz_Panel_Layout);
        quiz_Panel_Layout.setHorizontalGroup(
            quiz_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        quiz_Panel_Layout.setVerticalGroup(
            quiz_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        student_TabbedPane_.addTab("Quiz", quiz_Panel_);

        student_Panel_.add(student_TabbedPane_);

        side_Panel_.setLayout(new java.awt.GridLayout(2, 0));

        test_Info_Panel_.setLayout(new java.awt.BorderLayout(0, 5));

        student_Average_Score_Label_.setText("Average Score: ");
        test_Info_Panel_.add(student_Average_Score_Label_, java.awt.BorderLayout.NORTH);

        list_Of_Test_Panel_.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        test_List_.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        test_ScrollPane_.setViewportView(test_List_);

        list_Of_Test_Panel_.add(test_ScrollPane_);

        test_Description_Panel_.setLayout(new java.awt.BorderLayout());

        test_Description_Label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        test_Description_Panel_.add(test_Description_Label_, java.awt.BorderLayout.CENTER);

        take_Button_.setText("Take!");
        test_Description_Panel_.add(take_Button_, java.awt.BorderLayout.SOUTH);

        list_Of_Test_Panel_.add(test_Description_Panel_);

        test_Info_Panel_.add(list_Of_Test_Panel_, java.awt.BorderLayout.CENTER);

        side_Panel_.add(test_Info_Panel_);

        javax.swing.GroupLayout chat_Panel_Layout = new javax.swing.GroupLayout(chat_Panel_);
        chat_Panel_.setLayout(chat_Panel_Layout);
        chat_Panel_Layout.setHorizontalGroup(
            chat_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        chat_Panel_Layout.setVerticalGroup(
            chat_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        side_Panel_.add(chat_Panel_);

        student_Panel_.add(side_Panel_);

        main_Panel_.add(student_Panel_, "student_Card_");

        work_On_The_Test_Panel_.setLayout(new java.awt.BorderLayout());

        test_Panel_.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout question_Panel_Layout = new javax.swing.GroupLayout(question_Panel_);
        question_Panel_.setLayout(question_Panel_Layout);
        question_Panel_Layout.setHorizontalGroup(
            question_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        question_Panel_Layout.setVerticalGroup(
            question_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        question_ScrollPane_.setViewportView(question_Panel_);

        test_Panel_.add(question_ScrollPane_);

        javax.swing.GroupLayout task_Panel_Layout = new javax.swing.GroupLayout(task_Panel_);
        task_Panel_.setLayout(task_Panel_Layout);
        task_Panel_Layout.setHorizontalGroup(
            task_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        task_Panel_Layout.setVerticalGroup(
            task_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        task_ScrollPane_.setViewportView(task_Panel_);

        test_Panel_.add(task_ScrollPane_);

        work_On_The_Test_Panel_.add(test_Panel_, java.awt.BorderLayout.CENTER);

        submit_Button_.setText("Submit");
        work_On_The_Test_Panel_.add(submit_Button_, java.awt.BorderLayout.SOUTH);

        main_Panel_.add(work_On_The_Test_Panel_, "work_On_The_Test_Card_");

        getContentPane().add(main_Panel_, java.awt.BorderLayout.CENTER);

        footer_Panel_.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout footer_Panel_Layout = new javax.swing.GroupLayout(footer_Panel_);
        footer_Panel_.setLayout(footer_Panel_Layout);
        footer_Panel_Layout.setHorizontalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        footer_Panel_Layout.setVerticalGroup(
            footer_Panel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(footer_Panel_, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getMain_Panel_() {
        return main_Panel_;
    }

    public JPanel getQuestion_Panel_() {
        return question_Panel_;
    }

    public JButton getSubmit_Button_() {
        return submit_Button_;
    }

    public JTable getSubmitted_Test_Table_() {
        return submitted_Test_Table_;
    }

    public JButton getTake_Button_() {
        return take_Button_;
    }

    public JPanel getTask_Panel_() {
        return task_Panel_;
    }

    public JLabel getTest_Description_Label_() {
        return test_Description_Label_;
    }

    public JList<String> getTest_List_() {
        return test_List_;
    }

    public JLabel getStudent_Average_Score_Label_() {
        return student_Average_Score_Label_;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chat_Panel_;
    private javax.swing.JPanel footer_Panel_;
    private javax.swing.JPanel grade_Panel_;
    private javax.swing.JPanel header_Panel_;
    private javax.swing.JPanel list_Of_Test_Panel_;
    private javax.swing.JPanel main_Panel_;
    private javax.swing.JPanel question_Panel_;
    private javax.swing.JScrollPane question_ScrollPane_;
    private javax.swing.JPanel quiz_Panel_;
    private javax.swing.JPanel side_Panel_;
    private javax.swing.JLabel student_Average_Score_Label_;
    private javax.swing.JPanel student_Panel_;
    private javax.swing.JTabbedPane student_TabbedPane_;
    private javax.swing.JButton submit_Button_;
    private javax.swing.JScrollPane submitted_Test_ScrollPane;
    private javax.swing.JTable submitted_Test_Table_;
    private javax.swing.JButton take_Button_;
    private javax.swing.JPanel task_Panel_;
    private javax.swing.JScrollPane task_ScrollPane_;
    private javax.swing.JLabel test_Description_Label_;
    private javax.swing.JPanel test_Description_Panel_;
    private javax.swing.JPanel test_Info_Panel_;
    private javax.swing.JList<String> test_List_;
    private javax.swing.JPanel test_Panel_;
    private javax.swing.JScrollPane test_ScrollPane_;
    private javax.swing.JPanel work_On_The_Test_Panel_;
    // End of variables declaration//GEN-END:variables
}
